spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/moviedb
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
project:
  poster: /Users/pich/IdeaProjects/Spring boot/MovieAPI/posters
base:
  url: "http://localhost:8080"

jwt:
  secret: ylMxQoqPORxmvfszTntGqqBECJR7F8cGS3LZbKHoHfU=
  expiration: 86400000